#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-rredlist
Version  : 0.5.0
Release  : 4
URL      : https://cran.r-project.org/src/contrib/rredlist_0.5.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rredlist_0.5.0.tar.gz
Summary  : 'IUCN' Red List Client
Group    : Development/Tools
License  : MIT
Requires: R-crul
Requires: R-jsonlite
Requires: R-vcr
BuildRequires : R-crul
BuildRequires : R-jsonlite
BuildRequires : R-vcr
BuildRequires : clr-R-helpers

%description
The 'IUCN' Red List is a global list of threatened and endangered species.
    Functions cover all of the Red List 'API' routes. An 'API' key is required.

%prep
%setup -q -c -n rredlist

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532102780

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1532102780
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rredlist
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rredlist
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library rredlist
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library rredlist|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rredlist/DESCRIPTION
/usr/lib64/R/library/rredlist/INDEX
/usr/lib64/R/library/rredlist/LICENSE
/usr/lib64/R/library/rredlist/Meta/Rd.rds
/usr/lib64/R/library/rredlist/Meta/features.rds
/usr/lib64/R/library/rredlist/Meta/hsearch.rds
/usr/lib64/R/library/rredlist/Meta/links.rds
/usr/lib64/R/library/rredlist/Meta/nsInfo.rds
/usr/lib64/R/library/rredlist/Meta/package.rds
/usr/lib64/R/library/rredlist/NAMESPACE
/usr/lib64/R/library/rredlist/NEWS.md
/usr/lib64/R/library/rredlist/R/rredlist
/usr/lib64/R/library/rredlist/R/rredlist.rdb
/usr/lib64/R/library/rredlist/R/rredlist.rdx
/usr/lib64/R/library/rredlist/help/AnIndex
/usr/lib64/R/library/rredlist/help/aliases.rds
/usr/lib64/R/library/rredlist/help/paths.rds
/usr/lib64/R/library/rredlist/help/rredlist.rdb
/usr/lib64/R/library/rredlist/help/rredlist.rdx
/usr/lib64/R/library/rredlist/html/00Index.html
/usr/lib64/R/library/rredlist/html/R.css
